app:
  config:
    cassandra:
      page-size: 10

spring:
  cassandra:
    keyspace: "req10079266"
    schema-action: create_if_not_exists
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    port: 9042
    contact-points:
      - 127.0.0.1

